name: pkmn_app
description: Flutter app based on Pokemon Go.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.5
  
flutter:
  uses-material-design: true
  assets:
    - assets/campusMap2.jpg
    - assets/pokeball.png
    - assets/pokemon_list.csv
    - assets/sprites/

